"""Create publishers table

Revision ID: 02179d3c39f0
Revises: 6839b7aeb337
Create Date: 2025-02-25 05:12:15.746514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02179d3c39f0'
down_revision = '6839b7aeb337'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publishers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publishers')
    # ### end Alembic commands ###
