"""add created_at and updated_at columns on authors table

Revision ID: 98445f02d083
Revises: 9b868121e6f5
Create Date: 2025-03-03 02:18:00.509071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98445f02d083'
down_revision = '9b868121e6f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
